//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopProduct.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int empID { get; set; }
        public string empName { get; set; }
        public Nullable<System.DateTime> empDate { get; set; }
        public string empPhoto { get; set; }
        public string empAddress { get; set; }
        public Nullable<int> empSalary { get; set; }
        public Nullable<int> empBonus { get; set; }
        public Nullable<System.DateTime> empStartTime { get; set; }
        public string empEmail { get; set; }
        public string empPhone { get; set; }
        public string empPassword { get; set; }
        public Nullable<int> emPositon { get; set; }
        public Nullable<int> empRole { get; set; }
    
        public virtual EmployeesPosition EmployeesPosition { get; set; }
        public virtual EmployeesRole EmployeesRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
