//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopProduct.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Comments = new HashSet<Comment>();
            this.DetailsOrders = new HashSet<DetailsOrder>();
        }
    
        public int proID { get; set; }
        public string proName { get; set; }
        public Nullable<int> proPrice { get; set; }
        public string proPhoto { get; set; }
        public Nullable<int> proType { get; set; }
        public string proStatus { get; set; }
        public Nullable<int> proProducer { get; set; }
        public Nullable<int> proQuatity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsOrder> DetailsOrders { get; set; }
        public virtual ProducerType ProducerType { get; set; }
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual ProductType ProductType { get; set; }
        public virtual Rate Rate { get; set; }
    }
}
